[[drone]]
id = 1
connected_drone_ids = [2, 3, 4]
pdr = 0.95

[[drone]]
id = 2
connected_drone_ids = [1, 3]
pdr = 0.98

[[client]]
id = 101
connected_drone_ids = [1, 2]

[[client]]
id = 102
connected_drone_ids = [2]

[[server]]
id = 201
connected_drone_ids = [1, 2, 3, 4]