[package]
name = "dr_ones"
version = "0.1.0"
edition = "2021"

[dependencies]
wgl_repo_2024 = { path = "../WGL_repo_2024/" }
tokio = { version = "1", features = ["full"] }
rand = "0.8"
toml = "0.8.19"
serde = { version = "1.0.214", features = ["derive"] }