[[drone]]
id = 1
connected_node_ids = [2, 3]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1, 4, 6]
pdr = 0.03

[[drone]]
id = 3
connected_node_ids = [6, 1, 5]
pdr = 0.14

[[drone]]
id = 4
connected_node_ids = [2, 7]
pdr = 0.14

[[drone]]
id = 5
connected_node_ids = [3, 7]
pdr = 0.14

[[client]]
id = 6
connected_drone_ids = [3, 2]

[[server]]
id = 7
connected_drone_ids = [4, 5]