[[drone]]
id = 2
connected_node_ids = [1, 4]
pdr = 0.14

[[drone]]
id = 3
connected_node_ids = [1, 4, 6]
pdr = 0.14

[[drone]]
id = 4
connected_node_ids = [2, 3, 5]
pdr = 0.14

[[client]]
id = 1
connected_drone_ids = [3, 2]

[[server]]
id = 5
connected_drone_ids = [4]

[[server]]
id = 6
connected_drone_ids = [3]
