[[drone]]
id = 3
connected_node_ids = [1, 2, 5]
pdr = 0.14

[[drone]]
id = 4
connected_node_ids = [2, 1, 5]
pdr = 0.14

[[client]]
id = 1
connected_drone_ids = [3, 4]

[[client]]
id = 2
connected_drone_ids = [3, 4]

[[server]]
id = 5
connected_drone_ids = [3, 4]
